# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trinket.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "trinket.Request" do
    optional :name, :string, 1
  end
  add_message "trinket.Response" do
    repeated :gems, :message, 1, "trinket.Gem"
  end
  add_message "trinket.Gem" do
    optional :author_count, :uint32, 1
    repeated :authors, :string, 2
    optional :description, :string, 3
    optional :epoch_time, :uint64, 4
    optional :homepage, :string, 5
    repeated :licenses, :string, 6
    optional :name, :string, 7
    optional :summary, :string, 8
    optional :version, :message, 9, "trinket.Version"
  end
  add_message "trinket.Version" do
    optional :major, :uint32, 1
    optional :minor, :uint32, 2
    optional :teeny, :uint32, 3
    optional :patch, :uint32, 4
    optional :string, :string, 5
  end
end

module Trinket
  Request = Google::Protobuf::DescriptorPool.generated_pool.lookup("trinket.Request").msgclass
  Response = Google::Protobuf::DescriptorPool.generated_pool.lookup("trinket.Response").msgclass
  Gem = Google::Protobuf::DescriptorPool.generated_pool.lookup("trinket.Gem").msgclass
  Version = Google::Protobuf::DescriptorPool.generated_pool.lookup("trinket.Version").msgclass
end
