# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: trinket.proto for package 'trinket'

require 'grpc'
require 'trinket_pb'

module Trinket
  module Gems
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'trinket.Gems'

      rpc :gem, Request, Response
    end

    Stub = Service.rpc_stub_class
  end
end
